### PR TITLE
Added support for JSON feed

### LINKED ISSUE #80: JSON Feed Support?
Any plans on supporting the JSON Feed format?

https://jsonfeed.org/

Obviously JSON is easy enough to parse on it's own, but it would be great to be able to have it just work with this out of the box.

### PR DESCRIPTION
**Pull request by sudhanshuraheja**
Added support for JSON Feed 1.0 based on this specification - https://jsonfeed.org/version/1

* Support all fields except Hubs and JSON Feed Extensions
* Uses Jsoniter for parsing JSON, 3x faster at parsing JSON https://github.com/json-iterator/go
* Support for JSON feed in DetectFeedType
* Support for using JSON feed with the global Feed struct
* Support for translation of all known JSON feeds elements in global Feed except a few which are specified in comments as TODO
* Test coverage for all new code added to the codebase

Resolves #80

### CODE REVIEW

**Comment by mmcdole** [comment]
@sudhanshuraheja Would you be able to check if it is a JSON feed after the XML feeds?  In terms of popularity in the wild, I would expect RSS > Atom > JSONFeed.

I wouldn't want people to take the parsing hit for the least common case.

**Comment by sudhanshuraheja** [comment]
Makes sense, let me do that and update.

**Comment by nkanaev** [comment]
@sudhanshuraheja any progress on the feature? If no, I'm happy to pick up where you left off.

**Comment by mmcdole** [comment]
Closing since we got this merged in 164.

**Comment by mmcdole** [comment]
Thanks again for your contribution!

**Pull request closed without merging**
